<?php
/*
// print_r($block->getJobData());
$data = $block->getJobData();
$cnt = $block->getJobCount();
?>
<script type="text/javascript">
    google.charts.load("current", {packages:["timeline"]});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
        var container = document.getElementById('timeline');
        var chart = new google.visualization.Timeline(container);
        var dataTable = new google.visualization.DataTable();

        dataTable.addColumn({ type: 'string', id: 'job' });
        dataTable.addColumn({ type: 'string', id: 'label' });
        dataTable.addColumn({ type: 'string', role: 'tooltip' });
        dataTable.addColumn({ type: 'string', id: 'style', role: 'style' });
        dataTable.addColumn({ type: 'date', id: 'Start' });
        dataTable.addColumn({ type: 'date', id: 'End' });

        dataTable.addRows([
        <?php foreach ($block->getJobData() as $row): ?>
            ['<?= $row[0] ?>', '<?= $row[1] ?>', null, '#<?= $row[2] ?>',<?= $row[4] ?>, <?= $row[5] ?>],
        <?php endforeach; ?>
        ]);
        var options = {
            timeline: { showBarLabels: false },
            tooltip: { isHtml: true }
        };
        chart.draw(dataTable, options);
    }
</script>
<div id="timeline" style="height: <?= $cnt * 43; ?>px"></div>
 *
 */
?>
<?php
$jobCodes = $block->getAvailableJobCodes();
?>
<div class="timeline-wrapper">
    <div class="timeline-column">
        <div class="timeline-box">
            <div class="timeline-panel" style="width: <?php echo $block->getTimelinePanelWidth(); ?>px;">
                <div class="timeline-now" style="left: <?php echo $this->getNowline(); ?>px"><div class="timeline-arrow"></div></div>
                <div class="timeline-row timeline-hours">
                    <div class="timeline-element">
                        <?php for ($i = $block->getStarttime(); $i < $block->getEndtime(); $i += 60 * 60): ?>
                            <div class="timeline-hour"><span><?php echo $block->decorateTime($i, false); ?></span></div>
                        <?php endfor; ?>
                    </div>
                </div>

                <?php foreach ($jobCodes as $jobCode): /* @var $jobCode string */ ?>
                    <?php $schedules = $this->getSchedulesForCode($jobCode); ?>
                    <div class="timeline-row">
                        <div class="timeline-element timeline_<?php echo $jobCode; ?>">
                            <?php foreach ($schedules as $schedule): ?>
                                <?php echo $block->getScheduleResult($schedule); ?>
                                <?php
                                echo $this->getLayout()
                                    ->createBlock('Mygento\CronScheduler\Block\Adminhtml\Timeline\Detail')
                                    ->setSchedule($schedule)
                                    ->setOffset($block->getOffset($schedule))
                                    ->toHtml();
                                ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
<div class="timeline-leftcolumn">
    <div class="timeline-row hours">
        <div class="caption">

        </div>
    </div>

    <?php foreach ($jobCodes as $jobCode): /* @var $jobCode string */ ?>
        <div class="timeline-row">
            <div class="timeline-configuration">
                <?php echo $jobCode; ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>